#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
#


DOT_EMACS_ROOT = '../'
DEFAULT_DIR = 'manual-install/'
ELISP_LIST = {
   'auto-install' => {
    dir: DEFAULT_DIR,
    url: 'http://www.emacswiki.org/emacs/download/auto-install.el'
  },
  'tabbar' => {
    dir: DEFAULT_DIR,
    url: 'http://www.emacswiki.org/emacs/download/tabbar.el'
  },
  'auto-save-buffers' => {
    dir: DEFAULT_DIR,
    url: 'http://0xcc.net/misc/auto-save/auto-save-buffers.el'
  },
  'markdown-mode' => {
    dir: DEFAULT_DIR,
    url: 'http://jblevins.org/git/markdown-mode.git/plain/markdown-mode.el'
  }
}

download_command = :curl

def install_elisp(dir, url, command, elisp)
  install_dir = "#{DOT_EMACS_ROOT}#{dir}"

  if command == :curl
    sh "curl -X GET #{url} > #{install_dir}#{elisp}.el "
  end
end

def is_installed(elisp, dir)
  file_path = DOT_EMACS_ROOT + dir + elisp + '.el'
  File.exists?("#{file_path}")
end


desc "3rd party elispのwebからのinstall"
task :install_elisp do
  ELISP_LIST.each do |elisp, propaty|
    next if is_installed(elisp, propaty[:dir])

    puts "install #{elisp}...to #{propaty[:dir]}"
    if install_elisp(propaty[:dir], propaty[:url], download_command, elisp)
      puts "success!!"
    else
      puts "fail"
    end
  end
end
