#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
#


DOT_EMACS_ROOT = '../'
DEFAULT_DIR = 'manual-install/'
TMP_DIR = DOT_EMACS_ROOT + 'tmp/'
ELISP_LIST = {
   'auto-install' => {
    dir: DEFAULT_DIR,
    url: 'http://www.emacswiki.org/emacs/download/auto-install.el'
  },
  'tabbar' => {
    dir: DEFAULT_DIR,
    url: 'http://www.emacswiki.org/emacs/download/tabbar.el'
  },
  'auto-save-buffers' => {
    dir: DEFAULT_DIR,
    url: 'http://0xcc.net/misc/auto-save/auto-save-buffers.el'
  },
  'markdown-mode' => {
    dir: DEFAULT_DIR,
    url: 'http://jblevins.org/git/markdown-mode.git/plain/markdown-mode.el'
  },
  'groovy-mode' => {
    dir: DEFAULT_DIR,
    url: 'https://launchpad.net/groovy-emacs-mode/trunk/current-release/+download/emacs-groovy-mode_2011-06-29.tgz'
  },
  'dired-single' => {
    dir: DEFAULT_DIR,
    url: 'http://www.emacswiki.org/emacs/download/dired-single.el'
  }
}

download_command = :curl

def install_elisp_with_tgz(dir, url, command, elisp)
  install_dir = File.expand_path "#{DOT_EMACS_ROOT}#{dir}"
  FileUtils.cd(TMP_DIR) do
    sh "wget --no-check-certificate #{url}"
    sh "tar -zxvf #{File.basename url}"
    sh "cp *.el #{install_dir}"
    sh "rm *"
  end
end

def install_elisp_with_text(dir, url, command, elisp)
  install_dir = File.expand_path "#{DOT_EMACS_ROOT}#{dir}"
  if command == :curl
    sh "curl -X GET #{url} > #{install_dir}/#{elisp}.el "
  end
end

def install_elisp(dir, url, command, elisp)
  ext = File.extname(url.to_s)
  case ext
  when '.tgz'
    install_elisp_with_tgz(dir, url, command, elisp)
  when '.el'
    install_elisp_with_text(dir, url, command, elisp)
  else
    puts "unknown ext #{ext}"
  end
end

def is_installed(elisp, dir)
  file_path = DOT_EMACS_ROOT + dir + elisp + '.el'
  File.exists?("#{file_path}")
end


desc "3rd party elispのwebからのinstall"
task :install_elisp do
  ELISP_LIST.each do |elisp, propaty|
    next if is_installed(elisp, propaty[:dir])

    puts "install #{elisp}...to #{propaty[:dir]}"
    if install_elisp(propaty[:dir], propaty[:url], download_command, elisp)
      puts "success!!"
    else
      puts "fail"
    end
  end
end
